In [2]:
import pandas as pd

In [7]:
mg1 = pd.read_csv("/Users/sanhorn/Desktop/Internships/Econ Data Lab/IFLS5 Dataset/b3a_mg1.csv")
mg1

,hhid14_9,pid14,mg00x,mg01bx,mg01cx,mg01dx,mg01ex,mg01e,mg01d,mg01c,...,mg18e,mg19b,mg20b,mg20b1,mg20c,mg20d,hhid14,pidlink,version,module
0,1060000,1,3.0,3.0,3.0,3.0,3.0,62.0,12.0,1.0,...,NaN,1.0,1.0,3.0,1.0,1.0,10600,1060001,1.3,B3A_MG1
1,1060004,1,3.0,1.0,1.0,1.0,1.0,62.0,12.0,1.0,...,NaN,1.0,1.0,3.0,2.0,1.0,10651,1060004,1.3,B3A_MG1
2,1060000,7,3.0,1.0,1.0,3.0,3.0,62.0,12.0,14.0,...,NaN,1.0,1.0,3.0,1.0,1.0,10600,1060007,1.3,B3A_MG1
3,1060000,8,3.0,3.0,3.0,3.0,3.0,62.0,12.0,1.0,...,NaN,3.0,NaN,3.0,0.0,3.0,10600,1060008,1.3,B3A_MG1
4,1060004,2,3.0,1.0,1.0,3.0,3.0,62.0,12.0,14.0,...,NaN,1.0,1.0,3.0,1.0,1.0,10651,1065102,1.3,B3A_MG1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33961,321291100,3,3.0,3.0,3.0,3.0,3.0,62.0,73.0,71.0,...,NaN,3.0,NaN,3.0,0.0,3.0,3212911,321291103,1.3,B3A_MG1
33962,321291100,4,3.0,3.0,3.0,3.0,3.0,62.0,73.0,71.0,...,NaN,3.0,NaN,3.0,0.0,3.0,3212911,321291104,1.3,B3A_MG1
33963,321300000,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,NaN,NaN,1.0,0.0,3.0,3213000,321300001,1.3,B3A_MG1
33964,321300000,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,NaN,NaN,1.0,0.0,3.0,3213000,321300002,1.3,B3A_MG1
33965,321300000,3,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,NaN,NaN,1.0,0.0,3.0,3213000,321300003,1.3,B3A_MG1

In [3]:
mg2 = pd.read_csv("/Users/sanhorn/Desktop/Internships/Econ Data Lab/IFLS5 Dataset/b3a_mg2.csv")
mg2

,hhid14_9,pid14,movenum,mg21bx,mg21cx,mg21dx,mg21ex,mg21e,mg21d,mg21c,...,mg34a,mg34,mg35,mg36,mg39,mg40,hhid14,pidlink,version,module
0,1060000,1,1,3,3,3,3,62,12,1,...,NaN,3,NaN,NaN,3,NaN,10600,1060001,1.3,B3A_MG2
1,1060004,1,1,1,1,3,3,62,12,14,...,NaN,3,NaN,NaN,1,NaN,10651,1060004,1.3,B3A_MG2
2,1060004,1,2,3,3,3,3,62,12,1,...,NaN,1,2.0,AG,3,NaN,10651,1060004,1.3,B3A_MG2
3,1060000,7,1,3,3,3,3,62,12,1,...,NaN,3,NaN,NaN,3,NaN,10600,1060007,1.3,B3A_MG2
4,1060004,2,1,3,3,3,3,62,12,1,...,NaN,1,3.0,AG,3,NaN,10651,1065102,1.3,B3A_MG2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19804,321270000,8,2,1,1,3,3,62,73,73,...,NaN,3,NaN,NaN,1,NaN,3212700,321270008,1.3,B3A_MG2
19805,321270000,8,3,3,3,3,3,62,73,71,...,NaN,3,NaN,NaN,3,NaN,3212700,321270008,1.3,B3A_MG2
19806,321270004,2,1,3,3,3,3,62,73,71,...,NaN,3,NaN,NaN,3,NaN,3212751,321275102,1.3,B3A_MG2
19807,321280009,1,1,3,3,3,3,62,73,71,...,NaN,1,1.0,A,3,NaN,3212853,321280009,1.3,B3A_MG2
19808,321280000,12,1,3,3,3,3,62,73,71,...,NaN,3,NaN,NaN,3,NaN,3212800,321280012,1.3,B3A_MG2

In [23]:
common_hhids = set(mg1["hhid14_9"].unique()).intersection(set(mg2["hhid14_9"].unique()))
common_mg1 = mg1[mg1["hhid14_9"].isin(common_hhids)]
common_mg2 = mg2[mg2["hhid14_9"].isin(common_hhids)]

common_mg = pd.merge(common_mg1, common_mg2, on=["hhid14_9", "pid14"], how="outer")
common_mg = common_mg.sort_values(by=['hhid14_9', 'pid14'])

not_mg1 = mg1[~mg1["hhid14_9"].isin(common_hhids)]
not_mg2 = mg2[~mg2["hhid14_9"].isin(common_hhids)]

not_mg = pd.concat([not_mg1, not_mg2], sort=False)
not_mg = not_mg.sort_values(by=['hhid14_9', 'pid14'])

all_mg = pd.concat([common_mg, not_mg], ignore_index=True)
all_mg = all_mg.sort_values(by=['hhid14_9', 'pid14'])
all_mg = all_mg.reset_index(drop=True)

all_mg.to_csv('b3_migration.csv', index=False)

In [6]:
# tk1, tk2
tk1 = pd.read_csv("/Users/sanhorn/Desktop/Internships/Econ Data Lab/IFLS5 Dataset/b3a_tk1.csv")
tk2 = pd.read_csv("/Users/sanhorn/Desktop/Internships/Econ Data Lab/IFLS5 Dataset/b3a_tk2.csv")
tk3 = pd.read_csv("/Users/sanhorn/Desktop/Internships/Econ Data Lab/IFLS5 Dataset/b3a_tk3.csv")
tk4 = pd.read_csv("/Users/sanhorn/Desktop/Internships/Econ Data Lab/IFLS5 Dataset/b3a_tk4.csv")

common_hhid_12 = set(tk1["hhid14_9"].unique()).intersection(set(tk2["hhid14_9"].unique()))
common_tk1 = tk1[tk1["hhid14_9"].isin(common_hhid_12)]
common_tk2 = tk2[tk2["hhid14_9"].isin(common_hhid_12)]

common_tk_12 = pd.merge(common_tk1, common_tk2, on=["hhid14_9", "pid14"], how="outer")
common_tk_12 = common_tk_12.sort_values(by=['hhid14_9', 'pid14'])

not_tk1 = tk1[~tk1["hhid14_9"].isin(common_hhid_12)]
not_tk2 = tk2[~tk2["hhid14_9"].isin(common_hhid_12)]

not_tk_12 = pd.concat([not_tk1, not_tk2], sort=False)
not_tk_12 = not_tk_12.sort_values(by=['hhid14_9', 'pid14'])

all_12 = pd.concat([common_tk_12, not_tk_12], ignore_index=True)
all_12 = all_12.sort_values(by=['hhid14_9', 'pid14'])
all_12 = all_12.reset_index(drop=True)
all_12.to_csv('b3_tk12.csv', index=False)

/Users/sanhorn/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (135) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
# tk3, tk4
common_hhid_34 = set(tk3["hhid14_9"].unique()).intersection(set(tk4["hhid14_9"].unique()))
common_tk3 = tk3[tk3["hhid14_9"].isin(common_hhids)]
common_tk4 = tk4[tk4["hhid14_9"].isin(common_hhids)]

common_tk_34 = pd.merge(common_tk3, common_tk4, on=["hhid14_9", "pid14"], how="outer")
common_tk_34 = common_tk_34.sort_values(by=['hhid14_9', 'pid14'])

not_tk3 = tk3[~tk3["hhid14_9"].isin(common_hhids)]
not_tk4 = tk4[~tk4["hhid14_9"].isin(common_hhids)]

not_tk_34 = pd.concat([not_tk3, not_tk4], sort=False)
not_tk_34 = not_tk_34.sort_values(by=['hhid14_9', 'pid14'])

all_34 = pd.concat([common_tk_34, not_tk_34], ignore_index=True)
all_34 = all_mg.sort_values(by=['hhid14_9', 'pid14'])
all_34 = all_mg.reset_index(drop=True)

In [ ]:
# all_12, all_34
common_hhid_tk = set(all_12["hhid14_9"].unique()).intersection(set(all_34["hhid14_9"].unique()))
common_12 = all_12[all_12["hhid14_9"].isin(common_hhids)]
common_tk4 = all_34[all_34["hhid14_9"].isin(common_hhids)]

common_tk_34 = pd.merge(common_tk3, common_tk4, on=["hhid14_9", "pid14"], how="outer")
common_tk_34 = common_tk_34.sort_values(by=['hhid14_9', 'pid14'])

not_tk3 = tk3[~tk3["hhid14_9"].isin(common_hhids)]
not_tk4 = tk4[~tk4["hhid14_9"].isin(common_hhids)]

not_tk_34 = pd.concat([not_tk3, not_tk4], sort=False)
not_tk_34 = not_tk_34.sort_values(by=['hhid14_9', 'pid14'])

all_34 = pd.concat([common_tk_34, not_tk_34], ignore_index=True)
all_34 = all_mg.sort_values(by=['hhid14_9', 'pid14'])
all_34 = all_mg.reset_index(drop=True)